

CREATE table etf_metadata(
 	id bigint GENERATED BY DEFAULT AS IDENTITY,
    ticker character varying(10) COLLATE pg_catalog."default" NOT NULL UNIQUE,
	isin character varying(12) COLLATE pg_catalog."default" NULL,
	name character varying(50) COLLATE pg_catalog."default" NOT NULL,
	is_active bool DEFAULT True,
	created_at TIMESTAMPTZ DEFAULT now(),
	last_sync TIMESTAMPTZ NULL
)

TABLESPACE pg_default;


insert into etf_metadata
	(ticker, isin, name, is_active, created_at, last_sync)
values
	('IS3N.DE', NULL, 'Core MSCI EM IMI USD (Acc)', True, NOW(), NULL),
	('EUNA.DE', NULL, 'Global Aggregate Bond EUR (Acc)', True, NOW(), NULL),
	('EUNL.DE', NULL, 'Core MSCI World USD(Acc)', True, NOW(), NULL),
	('SWDA.MI', NULL, 'Global Found', True, NOW(), NULL),
	('VWCE.DE', NULL, 'Global ETF equity EUR (Acc)', True, NOW(), NULL),
	('QDVE.DE', NULL, 'USA Technological sector', True, NOW(), NULL),
	('EIMI.MI', NULL, 'Emergent Markets', True, NOW(), NULL),
	('VUSA.MI', NULL, 'S&P 500 index replica', True, NOW(), NULL),
	('AGGH.MI', NULL, 'Diversified Global Bond ', True, NOW(), NULL)