-- Table: public.etf_prices

-- DROP TABLE IF EXISTS public.etf_prices;

CREATE TABLE IF NOT EXISTS public.etf_prices
(
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    symbol character varying(10) COLLATE pg_catalog."default" NOT NULL,
    price_date date NOT NULL,
    open_price numeric(18,6),
    high_price numeric(18,6),
    low_price numeric(18,6),
    close_price numeric(18,6),
    volume bigint,
    created_at TIMESTAMPTZ DEFAULT now(),
    currency character varying(3) COLLATE pg_catalog."default" NOT NULL DEFAULT 'USD'::character varying,
    CONSTRAINT etf_prices_pkey PRIMARY KEY (id),
    CONSTRAINT etf_prices_symbol_price_date_key UNIQUE (symbol, price_date)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.etf_prices
    OWNER to etfinsight;
-- Index: idx_etf_prices_date

-- DROP INDEX IF EXISTS public.idx_etf_prices_date;

CREATE INDEX IF NOT EXISTS idx_etf_prices_date
    ON public.etf_prices USING btree
    (price_date DESC NULLS FIRST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;
-- Index: idx_etf_prices_symbol_date

-- DROP INDEX IF EXISTS public.idx_etf_prices_symbol_date;

CREATE INDEX IF NOT EXISTS idx_etf_prices_symbol_date
    ON public.etf_prices USING btree
    (symbol COLLATE pg_catalog."default" ASC NULLS LAST, price_date DESC NULLS FIRST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;