<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Npgsql" Version="10.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.0" />
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.23" />
<PackageReference Include="Hangfire.PostgreSql" Version="1.21.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../EtfInsight.Core/EtfInsight.Core.csproj" />
    <ProjectReference Include="../EtfInsight.Infrastructure/EtfInsight.Infrastructure.csproj" />
    <ProjectReference Include="../EtfInsight.DataQuality/EtfInsight.DataQuality.csproj" />
  </ItemGroup>

</Project>
