using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EtfInsight.Core.Services;
using Microsoft.Extensions.Logging;
using EtfInsight.Core.Configuration;
using EtfInsight.Core.Interfaces;
using Microsoft.Extensions.Options;
using System.Text;
using System.Text.Json;

namespace EtfInsight.Infrastructure.Services
{
    public class OllamaChatService : IChatService
    {
        private readonly HttpClient _httpClient;
        private readonly AISettings _aiSettings;
        private readonly ILogger<OllamaChatService> _logger;
        private readonly IEmbeddingGenerator _embeddingGenerator;
        private readonly ISemanticSearchRepository _semanticSearchRepository;

        public OllamaChatService(
            IOptions<AISettings> aiSettings,
            ILogger<OllamaChatService> logger,
            IHttpClientFactory httpClientFactory,
            IEmbeddingGenerator embeddingGenerator,
            ISemanticSearchRepository semanticSearchRepository)
        {
            _aiSettings = aiSettings.Value;
            _logger = logger;
            _httpClient = httpClientFactory.CreateClient("Ollama");
            _httpClient.BaseAddress = new Uri(_aiSettings.OllamaUrl);
            _httpClient.Timeout = TimeSpan.FromSeconds(60);
            _embeddingGenerator = embeddingGenerator;
            _semanticSearchRepository = semanticSearchRepository;
        }


        public async Task<string> AskAiAsync(string question)
        {
            try
            {
                _logger.LogInformation("Processing question: {Question}", question);

                // Step 1: Generate embedding for the question
                var questionEmbedding = await _embeddingGenerator.GenerateEmbeddingAsync(question);

                _logger.LogInformation("Question embedding generated with {Dimensions} dimensions",
                    questionEmbedding.Length);

                // Step 2: Perform semantic search to find relevant documents
                var searchResults = await _semanticSearchRepository.SearchAsync(questionEmbedding, limit: 5);
                var relevantDocs = searchResults.ToList();

                if (!relevantDocs.Any())
                {
                    _logger.LogWarning("No relevant documents found for the question");
                    return "I'm sorry, I couldn't find any relevant information to answer your question.";
                }

                _logger.LogInformation("Found {Count} relevant documents",
                    relevantDocs.Count());

                // Step 3: Build the augmented prompt
                var augmentedPrompt = BuildAugmentedPrompt(question, relevantDocs);
                _logger.LogInformation("Built augmented prompt with {Length} characters",
                    augmentedPrompt.Length);

                // Step 4: Send the augmented prompt to Ollama to generate a response
                var answer = await GenerateResponseAsync(augmentedPrompt);

                _logger.LogInformation("Generated answer with {Length} characters", answer.Length);

                return answer;

            }
            catch (System.Exception ex)
            {
                _logger.LogError(ex, "Failed to process AI question");
                throw new InvalidOperationException(
                    "Error during the processing of the question. Make sure Ollama is running.", ex);
            }
        }

        private string BuildAugmentedPrompt(string question, List<Core.DTOs.SearchResult> relevantDocs)
        {
            var contextBuilder = new StringBuilder();
            contextBuilder.AppendLine("AVAILABLE CONTEXT:");
            contextBuilder.AppendLine();

            for (int i = 0; i < relevantDocs.Count; i++)
            {
                var doc = relevantDocs[i];
                contextBuilder.AppendLine($"[ETF {i + 1}] {doc.Ticker}:");
                contextBuilder.AppendLine(doc.Content);
                contextBuilder.AppendLine($"(Relevance Score: {doc.Similarity:P1})");
                contextBuilder.AppendLine();
            }

            var prompt = $"You're an AI financial assistant expert in ETFs.{contextBuilder}" +
                         $"INSTRUCTIONS:" +
                         $" - Answer the question using ONLY the provided context." +
                         $" - If the answer cannot generated by the available information, reply: \"I don't have enough information to answer this question.\"." +
                         $" - Be accurate and concise in your answers." +
                         $" - Mention the source ETF(s) in your answer if applicable and relevant." +
                         $" - Answer in English." +
                         $"USER QUESTION: {question}" +
                         $"ANSWER:";

            return prompt;
        }

        private async Task<string> GenerateResponseAsync(string prompt)
        {
            var request = new OllamaGenerateRequest
            {
                Model = _aiSettings.ChatModel ?? "llama3.2",
                Prompt = prompt,
                Stream = false
            };

            var jsonOptions = new JsonSerializerOptions
            {
                PropertyNamingPolicy = JsonNamingPolicy.CamelCase
            };

            var json = JsonSerializer.Serialize(request, jsonOptions);
            var content = new StringContent(json, Encoding.UTF8, "application/json");

            _logger.LogInformation("Calling Ollama /api/generate endpoint with model {Model}",
                _aiSettings.ChatModel);

            var response = await _httpClient.PostAsync("/api/generate", content);
            response.EnsureSuccessStatusCode();

            var jsonResponse = await response.Content.ReadAsStringAsync();
            var result = JsonSerializer.Deserialize<OllamaChatResponse>(jsonResponse, jsonOptions);


            if (string.IsNullOrWhiteSpace(result?.Response))
            {
                throw new InvalidOperationException("Ollama returned empty response");
            }

            return result.Response.Trim();
        }
    }


    internal class OllamaGenerateRequest
    {
        public string Model { get; set; }
        public string Prompt { get; set; }
        public bool Stream { get; set; }
    }

    internal class OllamaChatResponse
    {
        public string? Response { get; set; }
        public bool Done { get; set; }
    }
}